### ISSUE TITLE
test test_book_store_account.py is failing

### ISSUE THREAD

**Issue by miniTeckel** [BurhanH/TestAutomationCourse-python-api-project#21]
Test "test_1_user_create" from test_book_store_account.py is failing with error "KeyError: 'username'"

**Comment by BurhanH** [comment]
Correct, a test run for the main branch - https://github.com/BurhanH/TestAutomationCourse-python-api-project/runs/6852941511?check_suite_focus=true

**Comment by BurhanH** [comment]
@val-kan Please review your code, especially line 41 - https://github.com/BurhanH/TestAutomationCourse-python-api-project/blame/main/tests/test_book_store_account.py#L41 

We need to fix it

**Comment by BurhanH** [comment]
Fixed!
